BEGIN;
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (61, 'AZ');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (73, 'Feyenoord');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (94, 'Vitesse');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (494, 'NEC');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (593, 'FC Twente');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (629, 'Ajax');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (637, 'NAC Breda');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (664, 'Go Ahead Eagles');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (669, 'Willem II');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (682, 'PSV');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (750, 'FC Utrecht');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (814, 'RKC Waalwijk');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (822, 'FC Dordrecht');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (919, 'Sparta Rotterdam');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (1016, 'PEC Zwolle');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (1053, 'SC Heerenveen');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (1073, 'De Graafschap');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (1128, 'ADO Den Haag');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (1403, 'Heracles Almelo');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (1433, 'Almere City');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (1435, 'SC Cambuur');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (1459, 'Fortuna Sittard');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (1652, 'Excelsior');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (2344, 'Roda JC Kerkrade');
INSERT INTO `mydatabase`.`team` (`id`, `name`) VALUES (2345, 'FC Groningen');
COMMIT;