services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:80"
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: