nelmio_cors:
  defaults:
    allow_origin: ['*']
    allow_credentials: true
    allow_methods: ['POST', 'GET', 'PUT', 'DELETE', 'OPTIONS']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Authorization']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['*']
      allow_methods: ['POST', 'GET', 'PUT', 'DELETE', 'OPTIONS']
      allow_headers: ['Content-Type', 'Authorization']


