nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ['*'] # Of specifiek: ['http://localhost:3000']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
  paths:
    '^/api/': ~

