<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4R4o3Ti\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4R4o3Ti/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4R4o3Ti.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4R4o3Ti\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4R4o3Ti\App_KernelDevDebugContainer([
    'container.build_hash' => '4R4o3Ti',
    'container.build_id' => '833ac148',
    'container.build_time' => 1733104201,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4R4o3Ti');
