<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX3Vo4iL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX3Vo4iL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX3Vo4iL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX3Vo4iL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX3Vo4iL\App_KernelDevDebugContainer([
    'container.build_hash' => 'X3Vo4iL',
    'container.build_id' => '64b98035',
    'container.build_time' => 1732741329,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX3Vo4iL');
